kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.19
      minVersion: 4.19.10
      maxVersion: 4.19.15
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages:
       - name: kubernetes-nmstate-operator
         channels:
         - name: stable
       - name: kubevirt-hyperconverged
         channels:
         - name: stable
       - name: compliance-operator
         channels:
         - name: stable
       - name: cluster-logging
         channels:
         - name: stable-6.3
       - name: loki-operator
         channels:
         - name: stable-6.3
       - name: metallb-operator
         channels:
         - name: stable
       - name: cluster-observability-operator
         channels:
         - name: stable
       - name: cluster-kube-descheduler-operator
         channels:
         - name: stable
       - name: netobserv-operator
         channels:
         - name: stable
       - name: local-storage-operator
       - name: mtv-operator
         channels:
         - name: release-v2.9
       - name: redhat-oadp-operator
         channels:
         - name: stable
       - name: fence-agents-remediation
         channels:
         - name: stable
       - name: node-healthcheck-operator
         channels:
         - name: stable
       - name: node-maintenance-operator
         channels:
         - name: stable
       - name: advanced-cluster-management
         channels:
         - name: release-2.14
       - name: self-node-remediation
         channels:
         - name: stable
       - name: odf-csi-addons-operator
         channels:
         - name: stable-4.19
       - name: odf-dependencies
         channels:
         - name: stable-4.19
       - name: odf-multicluster-orchestrator
         channels:
         - name: stable-4.19
       - name: odf-prometheus-operator
         channels:
         - name: stable-4.19
       - name: local-storage-operator
         channels:
         - name: stable
       - name: ocs-operator
         channels:
         - name: stable-4.19
       - name: ocs-client-operator
         channels:
         - name: stable-4.19
       - name: mcg-operator
         channels:
         - name: stable-4.19
       - name: recipe
         channels:
         - name: stable-4.19
       - name: rook-ceph-operator
         channels:
         - name: stable-4.19
       - name: ceph-csi-operator
         channels:
         - name: stable-4.19
       - name: odr-cluster-operator
         channels:
         - name: stable-4.19
       - name: odr-hub-operator
         channels:
         - name: stable-4.19
       - name: multicluster-engine
         channels:
         - name: stable-2.9
       - name: servicemeshoperator3
         channels:
         - name: stable-3.1
       - name: kiali-ossm
         channels:
         - name: stable
       - name: openshift-gitops-operator
         channels:
         - name: latest
       - name: cluster-observability-operator
         channels:
         - name: stable
       - name: tempo-product
         channels:
         - name: stable
       - name: advanced-cluster-management
         channels: [{name: "release-2.14"}]
       - name: amq-broker-rhel8
         channels: [{name: "7.12.x"}]
       - name: amq-broker-rhel9
         channels: [{name: "7.13.x"}]
       - name: cluster-kube-descheduler-operator
         channels: [{name: "stable"}]
       - name: cluster-logging
         channels: [{name: "stable-6.4"}]
       - name: cluster-observability-operator
         channels: [{name: "stable"}]
       - name: clusterresourceoverride
         channels: [{name: "stable"}]
       - name: compliance-operator
         channels: [{name: "stable"}]
       - name: container-security-operator
         channels: [{name: "stable-3.15"}]
       - name: dns-operator
         channels: [{name: "stable"}]
       - name: external-dns-operator
         channels: [{name: "stable-v1"}]
       - name: fence-agents-remediation
         channels: [{name: "stable"}]
       - name: ingress-node-firewall
         channels: [{name: "stable"}]
       - name: kubernetes-nmstate-operator
         channels: [{name: "stable"}]
       - name: kubevirt-hyperconverged
         channels: [{name: "stable"}]
       - name: lifecycle-agent
         channels: [{name: "stable"}]
       - name: local-storage-operator
         channels: [{name: "stable"}]
       - name: loki-operator
         channels: [{name: "stable-6.4"}]
       - name: metallb-operator
         channels: [{name: "stable"}]
       - name: mtv-operator
         channels: [{name: "release-v2.10"}]
       - name: multicluster-engine
         channels: [{name: "stable-2.9"}]
       - name: netobserv-operator
         channels: [{name: "stable"}]
       - name: nfd
         channels: [{name: "stable"}]
       - name: node-healthcheck-operator
         channels: [{name: "stable"}]
       - name: node-maintenance-operator
         channels: [{name: "stable"}]
       - name: node-observability-operator
         channels: [{name: "alpha"}]
       - name: odf-csi-addons-operator
         channels: [{name: "stable-4.20"}]
       - name: odf-dependencies
         channels: [{name: "stable-4.20"}]
       - name: odf-external-snapshotter-operator
         channels: [{name: "stable-4.20"}]
       - name: odf-multicluster-orchestrator
         channels: [{name: "stable-4.20"}]
       - name: odf-prometheus-operator
         channels: [{name: "stable-4.20"}]
       - name: openshift-builds-operator
         channels: [{name: "latest"}]
       - name: openshift-cert-manager-operator
         channels: [{name: "stable-v1"}]
       - name: openshift-custom-metrics-autoscaler-operator
         channels: [{name: "stable"}]
       - name: openshift-gitops-operator
         channels: [{name: "latest"}]
       - name: openshift-pipelines-operator-rh
         channels: [{name: "latest"}]
       - name: quay-bridge-operator
         channels: [{name: "stable-3.15"}]
       - name: quay-operator
         channels: [{name: "stable-3.15"}]
       - name: redhat-oadp-operator
         channels: [{name: "stable"}]
       - name: rhacs-operator
         channels: [{name: "stable"}]
       - name: rhcl-operator
         channels: [{name: "stable"}]
       - name: rhods-operator
         channels: [{name: "stable"}]
       - name: rhsso-operator
         channels: [{name: "stable"}]
       - name: rook-ceph-operator
         channels: [{name: "stable-4.20"}]
       - name: secrets-store-csi-driver-operator
         channels: [{name: "stable"}]
       - name: self-node-remediation
         channels: [{name: "stable"}]
       - name: servicemeshoperator
         channels: [{name: "stable"}]
       - name: servicemeshoperator3
         channels: [{name: "stable"}]
       - name: submariner
         channels: [{name: "stable-0.21"}]
       - name: tempo-product
         channels: [{name: "stable"}]
  
  additionalImages:
    - name: registry.redhat.io/ubi8/ubi:latest
    - name: registry.redhat.io/rhel8/support-tools
